# Based on the first reply here: https://stackoverflow.com/q/73798925
# and related details here https://github.com/GuillaumeFalourd/poc-github-actions/blob/main/.github/workflows/12-run-workflow.yml
name: Status Notification

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types: [completed]

permissions:
  actions: read
  contents: read
jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This build's CI URL is ${{ env.CI_BUILD_URL }}."
      - run: echo "The CI workflow's status was ${{ github.event.workflow_run.conclusion}}."
      - name: ntfy-failed-notifications
      # https://github.com/marketplace/actions/ntfy_action docs/examples
        uses: niniyas/ntfy-action@master
        with:
          url: 'https://ntfy.sh'
          topic: '${{ secrets.NTFY_TOPIC }}'
          tags: action
          details: "Workflow status was ${{ github.event.workflow_run.conclusion}}"
          actions: 'default'
